name:                compiler
version:             0.1.0
github:              "andrewrmack/compiler"
license:             BSD3
author:              "Andrew Mack"
maintainer:          "andrewrmack@gmail.com"
copyright:           "2018 Andrew Mack"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/andrewrmack/compiler#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  build-tools:
    - alex
    - happy
  dependencies:
    - lens
    - deepseq
    - text
  ghc-options:
    - -O2
    - -Wall

executables:
  compiler:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    - -Wall
    dependencies:
    - compiler
    - optparse-applicative
    - text
    other-modules:
    - Paths_compiler

tests:
  compiler-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - compiler
    - process

benchmarks:
  compiler-benchmarks:
    main:                Bench.hs
    source-dirs:         benchmarks
    dependencies:
    - base
    - compiler
    - criterion
    - deepseq
    - text
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
